ktxCoreVersion              = 1.19.0
androidXVersion             = 1.0.0
appCompatVersion            = 1.8.0
multiDexVersion             = 2.0.1
archLifecycleVersion        = 2.11.0
liveDataVersion             = 2.11.0
pagingVersion               = 3.5.1
mdcVersion                  = 1.14.0
juniversalchardetVersion    = 2.5.0
gsonVersion                 = 2.14.0

POM_ARTIFACT_ID             = devbricksx
POM_DESCRIPTION             = DevBricks eXetrems
