{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.dailystudio",
    "module": "DevKitPlugin",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DevKitPlugin-0.5.0.jar",
          "url": "DevKitPlugin-0.5.0.jar",
          "size": 16733,
          "sha512": "8eadcc7fb12876d278e8a38e953a8e8f9221e7c50dabbbeb3430a8a2c930cd898910c6d8c8b32d87e33e6979e9532963f13fd5c0f2b7581551ae5b389211bcc1",
          "sha256": "6895a4d4e75108eb152d3809b1165124fc7d60efa0b6b3fad67aa1164be761cd",
          "sha1": "94495dec68fa579185adfbfceb58adf9df48d4cd",
          "md5": "253670ed3726d78d396879fd07145fd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.7.22-1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "DevKitPlugin-0.5.0.jar",
          "url": "DevKitPlugin-0.5.0.jar",
          "size": 16733,
          "sha512": "8eadcc7fb12876d278e8a38e953a8e8f9221e7c50dabbbeb3430a8a2c930cd898910c6d8c8b32d87e33e6979e9532963f13fd5c0f2b7581551ae5b389211bcc1",
          "sha256": "6895a4d4e75108eb152d3809b1165124fc7d60efa0b6b3fad67aa1164be761cd",
          "sha1": "94495dec68fa579185adfbfceb58adf9df48d4cd",
          "md5": "253670ed3726d78d396879fd07145fd0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DevKitPlugin-0.5.0-javadoc.jar",
          "url": "DevKitPlugin-0.5.0-javadoc.jar",
          "size": 261,
          "sha512": "1b01a5d95dd51563596d0ce4de1d4f153053b74bdd1875b770f49426b8d02a0526d2447bb107572f302fbad9a65d9865274bc0e62cd306dca82df2342965b7ef",
          "sha256": "7e5885de01d98e2617249683d671239b65e69c02a18ce37436518fb848d8c068",
          "sha1": "a53a2b996e782fd716ca19a66bb7d8f9d774aa17",
          "md5": "c4366c02d6b339ba24757a27c281b1ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DevKitPlugin-0.5.0-sources.jar",
          "url": "DevKitPlugin-0.5.0-sources.jar",
          "size": 3076,
          "sha512": "023a2dcce58c17ae5c4bf775aff7870afe2e1373735d67eadc5ad57580b5ecf5802f20dfdf2d85375894a213cdafc1b1e84dc5fe5a68ca15b840e5a0b3f62d7e",
          "sha256": "122e8166a88f0bf27405f70e380253627ef63fd5280b3cda16d80c2c5c79f8a5",
          "sha1": "80efe0dabc564d57aa9c751ac08a060ad3ce0e95",
          "md5": "ed891943530edd62133400dd46173518"
        }
      ]
    }
  ]
}
