{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.dailystudio",
    "module": "DevKitPlugin",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "DevKitPlugin-0.5.0.jar",
          "url": "DevKitPlugin-0.5.0.jar",
          "size": 16209,
          "sha512": "c5443a226f2abaee935380460c744529d39807e65e8cee37438f364b932a58944cae355a4f23d483f3220a2bd9f95d6adbfce948ff3a83acc7fe8686a712cc41",
          "sha256": "9bdad54dc60efed3c487009afe7deda88252608ecc9bf92197206e13c7f68100",
          "sha1": "eb019f0e821c17b3d2e9ec7705f9c189831afee5",
          "md5": "e0d7f2af608850cfbe7bc73e26d47724"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.7.10-1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "DevKitPlugin-0.5.0.jar",
          "url": "DevKitPlugin-0.5.0.jar",
          "size": 16209,
          "sha512": "c5443a226f2abaee935380460c744529d39807e65e8cee37438f364b932a58944cae355a4f23d483f3220a2bd9f95d6adbfce948ff3a83acc7fe8686a712cc41",
          "sha256": "9bdad54dc60efed3c487009afe7deda88252608ecc9bf92197206e13c7f68100",
          "sha1": "eb019f0e821c17b3d2e9ec7705f9c189831afee5",
          "md5": "e0d7f2af608850cfbe7bc73e26d47724"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DevKitPlugin-0.5.0-javadoc.jar",
          "url": "DevKitPlugin-0.5.0-javadoc.jar",
          "size": 261,
          "sha512": "1b01a5d95dd51563596d0ce4de1d4f153053b74bdd1875b770f49426b8d02a0526d2447bb107572f302fbad9a65d9865274bc0e62cd306dca82df2342965b7ef",
          "sha256": "7e5885de01d98e2617249683d671239b65e69c02a18ce37436518fb848d8c068",
          "sha1": "a53a2b996e782fd716ca19a66bb7d8f9d774aa17",
          "md5": "c4366c02d6b339ba24757a27c281b1ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DevKitPlugin-0.5.0-sources.jar",
          "url": "DevKitPlugin-0.5.0-sources.jar",
          "size": 2969,
          "sha512": "bb684ba4842bd85304c846938e80e732798df8b41fb4d16dbabf9edcb1a7d53de2e4af7f69e71a1196ad86550259c18d8218f1e02681810184bb13536077f8b9",
          "sha256": "56ca5d24abf5189fbefa74040161677f9a5407fd77b56bd76f2367bbbb5ead26",
          "sha1": "e6cd747e45b2e67a6294d31c9dd8ef797d8f376a",
          "md5": "733e1f63867e77805ca120f850d6c805"
        }
      ]
    }
  ]
}
